app:
  name: task-agent
  env: dev
  watch: false

log:
  level: info
  format: json
  path: logs/app.log
  max_size: 200
  max_age: 60
  max_backups: 60
  compress: true
  log_to_console: false

observability:
  enabled: false
  addr: ":9090"
  metrics_path: /metrics
  health_path: /health
  otel:
    endpoint: "alloy.com:4318"
    protocol: http
    logs:
      enabled: false
    traces:
      enabled: false
  tracing:
    enabled: false
    endpoint: ""
